### ISSUE TITLE
PolyCapture: Excessive compression of video files

### ISSUE THREAD

**Issue by RainerZufall9393** [appaheadgmbh/support#26]
I made a few test recordings today to see how the video quality with PolyCapture compares to QuickTime and internal camera recording. I used my Sony A6600 (4K video quality) with Elgato CamLink 4K.

However, I noticed that PolyCapture reproduces the color of the camera exactly (very good! QuickTime can't do that).

But the video quality was definitely lower with PolyCapture. I have a black background and I could clearly see compression artifacts there.

Could you include a quality option that is still based on HEVC but preserves the quality much better?

---

**Update: I think it's because of a too low bitrate**

**Comment by martinlexow** [comment]
The video quality of screen recordings should have significantly improved starting from version 1.4 🚀

I suspect that, in the medium term, I’ll need to add more options to the app, allowing users to adjust compression and codec settings individually. When many recordings are running in parallel, the maximum possible write speed of the SSD/HDD can quickly become a bottleneck. With a single recording, this is, of course, less of an issue. I’m working on a solution!

Since these topics are related, I’d like to continue the discussion [in this issue](https://github.com/appaheadgmbh/support/issues/31) and close this thread.

Thank you for the detailed feedback, @RainerZufall9393!
