### ISSUE TITLE
Mediocre Transcription Quality or Repeated Text with Very Long Files

### ISSUE THREAD

**Issue by ERSCORK** [appaheadgmbh/support#40]
Thanks a lot for the app. Currently I am having issues with AI Transcription when dealing with long files. I have lectures that are close to 3 hours long. Sometimes the transcript crashes from the start sometimes 40 min into the transcript. Here are few examples:

"897
0:41:30,100 --> 0:41:32,170
yourselves a quick cup of tea. OK.

898
0:41:32,180 --> 0:41:39,190
[BLANK_AUDIO]

Rest is 

1454
2:08:42,200 --> 2:08:52,190
[BLANK_AUDIO]

1455
2:08:52,200 --> 2:09:10,200
[BLANK_AUDIO] [BLANK_AUDIO]"

I have it set at 2.5 seconds but sometimes it gets stuck 

"3308
2:33:23,160 --> 2:33:24,950
or tidal energy

3309
2:33:24,960 --> 2:51:07,820"

and then back to normal. 

Sometimes it get stuck 

"1
0:00:00,080 --> 0:00:00,630
(ლლ)

2
0:00:00,640 --> 0:00:23,820
ᴅᴃᴄᴅᴅᴅ language

3
0:00:24,820 --> 0:00:27,820
. .

4
0:00:35,230 --> 0:00:53,690
if

5
0:00:53,700 --> 0:00:57,510
starter

6
0:00:57,520 --> 0:01:03,170
r Woman’s in the

7
0:01:03,180 --> 0:01:06,530
process."
 
and is like that for 3 hours. Not really sure what is up with it. Also the report problem or suggest feature button in the app doesnt work. It doesnt do anything.

**Comment by martinlexow** [comment]
Thank you for your bug report! 

**App crash when transcribing a very long file**: My first guess would be that your Mac might not have enough free RAM. In this case, it might help to close other apps that may have a high memory demand while transcribing. Splitting your 3-hour file into smaller segments could also be beneficial.

If you’re using an older Mac with an Intel processor, it might also help to select the _Speech Recognition_ option instead of Whisper under “Transcription Engine” in the settings. _Speech Recognition_ uses significantly fewer hardware resources, is generally faster on Intel Macs, but unfortunately, it is also less accurate compared to Whisper.

**The transcript is inaccurate or contains repetitions**: This can have various causes, such as insufficient quality of the original audio/video file. With the update to version 2.9, I’ve added a new option: In the settings, you can now prioritize whether the transcript should be created quickly or accurately. Additionally, you can now preselect a language. If the correct language is preselected and “precision” is prioritized, creating the transcript will take longer—but resulting in significantly better quality.

![Screenshot 2024-11-25 at 16 40 23](https://github.com/user-attachments/assets/5be34ea9-7779-4524-9cf9-bd69ba0e6f1a)

**The transcript preview freezes, and the cursor turns into a beach ball**: This issue has been fixed with the latest update to version 2.9.

**_Report problem_ and _Suggest feature_ buttons not working:** I just tested this again successfully. After pressing one of the buttons, your preferred mail app should open with a new message.
