### ISSUE TITLE
Screen recording MOV file can't open

### ISSUE THREAD

**Issue by C47Joe** [appaheadgmbh/support#45]
![CleanShot 2024-10-22 at 21 29 15@2x](https://github.com/user-attachments/assets/fbb3690a-902d-47c5-b007-7a96040ed441)

**Comment by djpowers** [comment]
Reported in #43

**Comment by mubalara69** [comment]
I have the same exact problem. By uninstalling and reinstalling doesn’t help. I can get by recording a single screen , but when multiple are involved, it doesn’t work. I already have screen recording software that does single screens pretty well, but I signed up only because it said it can simultaneously record. Love the developer, but this is not working , and would appreciate a fix asap. I have also written directly with the details and the screen recordings and the images.

https://github.com/user-attachments/assets/aa5e99bf-97e0-4013-bc5e-e519c4c4d8d0

**Comment by martinlexow** [comment]
Hi everyone — thanks for the bug report! This issue was already [discussed here](https://github.com/appaheadgmbh/support/issues/43), and it seems that I was able to fix it with Version 1.6, which is available as of today. 🥳

I’d be happy if you found the time to test the update. Please leave feedback in the [linked thread](https://github.com/appaheadgmbh/support/issues/43), as I’ll be closing this one now.
