### ISSUE TITLE
ScreenCaptureKit continues to show that recording is in progress, even though the app has been closed

### ISSUE THREAD

**Issue by wesbos** [appaheadgmbh/support#54]
I quit the app and this UI persists. I don't see polycapture in my processes - is there another named process running that I can kill? 

<img width="312" alt="Screenshot 2024-12-13 at 10 13 42 AM" src="https://github.com/user-attachments/assets/afad6b54-1ff2-444e-914a-0ade5f509f00" />

<img width="107" alt="Screenshot 2024-12-13 at 10 14 31 AM" src="https://github.com/user-attachments/assets/064d4a79-c223-4ecd-9eb9-69ab70bae7f2" />

**Comment by martinlexow** [comment]
PolyCapture does not use any helper processes. This means that as soon as the app itself is closed, it no longer executes any code. Did you stop the recording yourself before closing the app? Is this issue reproducible on your end (and if so, how)? Otherwise, I would assume it’s a bug in ScreenCaptureKit itself.

**Comment by wesbos** [comment]
Ahh yeah, If I remember correctly the UI to stop recording froze so I quit the app.  Likely was a bug out of your control
